### ISSUE TITLE
__getitem__ demands a Python long integer

### ISSUE THREAD

**Issue by jacobbond** [bertiniteam/b2#49] opened 2016-09-01 02:18 UTC
When trying to get an item out of a VectorXmp, `__getitem__` demands a Python long integer.  It doesn't actually affect functionality and it can be worked around in code with `long(str(index))`.

```
sage: y_end[1]
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-53-4e4a51777556> in <module>()
----> 1 y_end[Integer(1)]

ArgumentError: Python argument types in
    VectorXmp.__getitem__(VectorXmp, Integer)
did not match C++ signature:
    __getitem__(Eigen::Matrix<bertini::complex, -1, 1, 0, -1, 1>, long)
sage: y_end[1L]
(0.0000000000000000e+00, 0.0000000000000000e+00)
```

**Comment by ofloveandhate** [comment] 2016-09-01 17:50
is the (a) fix to provide functions accepting int's?  

can you confirm this issue also exists with VectorXd?

**Comment by jacobbond** [comment] 2016-09-01 21:19
Yes, it does happen with VectorXd:

```
sage: floats = [float(n) for n in range(5)]
sage: VectorXd(floats)[0]
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-32-d82c085cbe41> in <module>()
----> 1 VectorXd(floats)[Integer(0)]

ArgumentError: Python argument types in
    VectorXd.__getitem__(VectorXd, sage.rings.integer.Integer)
did not match C++ signature:
    __getitem__(Eigen::Matrix<std::complex<double>, -1, 1, 0, -1, 1>, long)
sage: VectorXd(floats)[0L]
0j
```

I don't anticipate ever needing a vector longer than `INT_MAX`, but I can't speak for others.  I did find that Python's `int`s are implemented using `long`s ([here](https://docs.python.org/2/library/stdtypes.html#numeric-types-int-float-long-complex)), so there is kind of a disconnect between what Python might pass as an `int` and what C++ can accept as an `int`.

**Comment by ofloveandhate** [comment] 2016-09-01 22:51
this is a [minieigen](https://github.com/eudoxos/minieigen) problem.  can you file an issue there, and refer to it from here?

**Comment by jacobbond** [comment] 2016-09-01 23:31
Filed with [minieigen](https://github.com/eudoxos/minieigen) as [#14](https://github.com/eudoxos/minieigen/issues/14).

**Comment by ofloveandhate** [comment] 2016-09-01 23:33
thanks.  eudoxus has been responsive to me in the past, so i am hopeful.  we'll watch their response, and help if we need to, k?

**Comment by jacobbond** [comment] 2016-09-02 00:34
Sounds good.

**Comment by eudoxos** [comment] 2016-09-03 06:14
From your error message:
 
    ArgumentError: Python argument types in
         VectorXd.__getitem__(VectorXd, sage.rings.integer.Integer)

you are passing sage.rings.integer.Integer as integer type, not Python's int. It seems that SAGE somehow automatically converts integer literals to sage.rings.integer.Integer; that is the cause of the problem. `boost::python` converts builtin integer types (builtins.int to c++ int/long/size_t/...) automatically, but not custom integer types.

There is nothing minieigen can do with this; I'd suggest you ask them to avoid this intrusive behavior. Another option is to write a `boost::python` module which will register an automatic converter from `sage.rings.integer.Integer` to `builtins.int`.

If you agree, I will close the issue in minieigen.

**Comment by jacobbond** [comment] 2016-09-03 14:36
Yeah, that's obviously a me problem.  I guess I didn't even think about `Integer` (as it's simply called in the first example) being different from `int`.

**Closed** 2016-09-03 14:36 UTC
Labels: dependency - minieigen, product - pybertini
